services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - FTP_BASE=/var/www/html/
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - FTP_HOST=ftp
      - FTP_SSL=false
      - FS_METHOD=direct
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
  redis:
    container_name: redis
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
  ftp:
    container_name: ftp
    networks:
      - inception
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    restart: always
  static-site:
    container_name: static-website
    networks:
      - inception
    build:
      context: requirements/bonus/static-website
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:80"
    restart: always


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/notart/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/notart/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge
